### ISSUE TITLE
sshd pre-login banner to alert people to the pi user change?

### ISSUE THREAD

**Issue by trejan** [RPi-Distro/userconf-pi#1]
sshd has the ability to send a pre-login banner by setting Banner in /etc/sshd_config to point to a text file e.g. /etc/sshd_banner. A message about the pi user no longer being accessible by default could be added in there. userconf-pi can delete the notification banner and remove the Banner config from /etc/sshd_config once it has run.

This should help with some of the current confusion about the pi user change.

**Comment by XECDesign** [comment]
Good idea

By the time we release a new image, the message probably won't benefit a lot of people. But, it's probably worth having anyway.

Thanks
