### ISSUE TITLE
/boot/userconf changes boot 

### ISSUE THREAD

**Issue by LazeMSS** [RPi-Distro/userconf-pi#2]
I tried many times now to make a headless RPI boot and setting the user and password using the new /boot/userconf.

And it works great except for one thing - it always set the login default to automatic text login.
I don't think this is the expected behavior. 

In my "image" i remove /etc/systemd/system/getty@tty1.service.d/autologin.conf and run systemctl --quiet set-default multi-user.target
, but the problem seems to be that when the userconf-service is handling the userconf  - the flow seems to be like this:

Userconf-service get to this line (which is rename but also set the new password):
- https://github.com/RPi-Distro/userconf-pi/blob/master/userconf-service#L98

Which then will hit this:
- https://github.com/RPi-Distro/userconf-pi/blob/master/userconf#L35

Which again will hit this:
- https://github.com/RPi-Distro/userconf-pi/blob/602561ba910749c114fec1e5b7218b45e770416e/cancel-rename#L28

Thereby calling raspi-config to set it to B2 Console Autologin

Im not sure why renaming the username or/and setting the password should cause any changes to the login behavior but I might be missing something

**Comment by XECDesign** [comment]
I think the way to resolve it is for us to save the boot behaviour to a file and then restore it.

I'll see what I can do for the next release. Thanks

**Comment by LazeMSS** [comment]
Thanks - I have basically removed in my local images. I can't really figure out why the userconf needs to run the cancel-rename always and reset the login option.
