### ISSUE TITLE
Unable to load SSH public keys before first boot.

### ISSUE THREAD

**Issue by videoman** [RPi-Distro/userconf-pi#3]
If you are requiring headless to set a password, please provide a way to load a set of public SSH keys (ed25519, RSA, etc) on the user after it has been renamed, and then disable password authentication for all users after boot. This is way more secure, vs renaming users and changing passwords. I'd rather the distro uses this as a default vs trying to manage passwords of these devices. Maybe have the first startup look for a /boot/ssh_pubkeys (one public key/line) and it will add the public keys to the user, and then turn off password auth.

**Comment by XECDesign** [comment]
> please provide a way to load a set of public SSH keys (ed25519, RSA, etc)

We'd recommend rpi-imager for that.

Once cloud-init is further along, we may have something in the base distro to do that, but for now it's outside the scope of what this tool is for.
